basePath: /api/v1
definitions:
  handler.User:
    properties:
      email:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: Example API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Returns list of all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.User'
            type: array
      summary: Get all users
      tags:
      - users
swagger: "2.0"
